src/Entity/Covoiturage.php
<?php

namespace App\Entity;

use App\Repository\CovoiturageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CovoiturageRepository::class)]
class Covoiturage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_depart = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_depart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $date_arrivee = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $heure_arrivee = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $statut = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column]
    private ?float $prix_personne = null;

    #[ORM\ManyToOne(inversedBy: 'covoiturages_depart')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $lieu_depart = null;

    #[ORM\ManyToOne(inversedBy: 'covoiturages_arrivees')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $lieu_arrivee = null;

    #[ORM\ManyToOne(inversedBy: 'covoiturages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Voiture $voiture = null;

    /**
     * @var Collection<int, Participation>
     */
    #[ORM\OneToMany(targetEntity: Participation::class, mappedBy: 'covoiturage', orphanRemoval: true)]
    private Collection $participations;

    public function __construct()
    {
        $this->participations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepart(): ?\DateTime
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTime $date_depart): static
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getHeureDepart(): ?\DateTime
    {
        return $this->heure_depart;
    }

    public function setHeureDepart(\DateTime $heure_depart): static
    {
        $this->heure_depart = $heure_depart;

        return $this;
    }

    public function getDateArrivee(): ?\DateTime
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTime $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getHeureArrivee(): ?\DateTime
    {
        return $this->heure_arrivee;
    }

    public function setHeureArrivee(\DateTime $heure_arrivee): static
    {
        $this->heure_arrivee = $heure_arrivee;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): static
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getPrixPersonne(): ?float
    {
        return $this->prix_personne;
    }

    public function setPrixPersonne(float $prix_personne): static
    {
        $this->prix_personne = $prix_personne;

        return $this;
    }

    public function getLieuDepart(): ?Ville
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(?Ville $lieu_depart): static
    {
        $this->lieu_depart = $lieu_depart;

        return $this;
    }

    public function getLieuArrivee(): ?Ville
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(?Ville $lieu_arrivee): static
    {
        $this->lieu_arrivee = $lieu_arrivee;

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipations(): Collection
    {
        return $this->participations;
    }

    public function addParticipation(Participation $participation): static
    {
        if (!$this->participations->contains($participation)) {
            $this->participations->add($participation);
            $participation->setCovoiturage($this);
        }

        return $this;
    }

    public function removeParticipation(Participation $participation): static
    {
        if ($this->participations->removeElement($participation)) {
            // set the owning side to null (unless already changed)
            if ($participation->getCovoiturage() === $this) {
                $participation->setCovoiturage(null);
            }
        }

        return $this;
    }

}

src/Controller/CovoiturageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\CovoiturageRepository;
use App\Repository\ParticipationRepository;
use App\Entity\Covoiturage;
use App\Entity\Participation;
use Doctrine\ORM\EntityManagerInterface;
use App\Service\ItineraireService;
use App\Form\CovoiturageFormType;
use App\Form\FiltresFormType;
use App\Form\ItineraireFormType;
use App\Form\DetailFormType;
use Doctrine\ODM\MongoDB\DocumentManager;
use App\Document\Avis;

final class CovoiturageController extends AbstractController
{

    #[Route('/covoiturage/d/{id}', name: 'app_delete_covoiturage')]
    public function delete(int $id, CovoiturageRepository $covoiturageRepository, EntityManagerInterface $entityManager): Response
    {

        $covoiturage = $covoiturageRepository->find($id);

        $chauffeurCredits = 0;

        foreach($covoiturage->getParticipatione() as $participation) {
            $participation->getPassager()->setCredits($participation->getPassager()->getCredits() + $covoiturage->getPrixPersonne());
            $entityManager->persist($participation);
        }

        $entityManager->remove($covoiturage);
        $entityManager->flush();

        return $this->redirectToRoute('app_covoiturages');

    }

    #[Route('/covoiturage/s/{id}', name: 'app_annuler_covoiturage')]
    public function annuler(
        int $id, 
        CovoiturageRepository $covoiturageRepository, 
        ParticipationRepository $participationRepository, 
        EntityManagerInterface $entityManager
    ): Response
    {

        /** @var User $user */
        $user = $this->getUser();

        $covoiturage = $covoiturageRepository->find($id);
        $participation = $participationRepository->findOneBy([
            'covoiturage' => $covoiturage,
            'passager' => $user
        ]);

        $entityManager->remove($participation);
        $entityManager->flush();

        return $this->redirectToRoute('app_participations');

    }

    #[Route('/covoiturage/m/{id}', name: 'app_statut_covoiturage')]
    public function statut(
        int $id, 
        CovoiturageRepository $covoiturageRepository, 
        ParticipationRepository $participationRepository, 
        EntityManagerInterface $entityManager
    ): Response
    {

        /** @var User $user */
        $user = $this->getUser();

        $covoiturage = $covoiturageRepository->find($id);

        $statut = $covoiturage->getStatut();

        if ($statut === 'planifié') {
            $covoiturage->setStatut('démarré');
        } elseif ($statut === 'démarré') {
            $covoiturage->setStatut('arrivé');
        } elseif ($statut = 'arrivé') {
            // send mail
        }
        
        $entityManager->persist($covoiturage);
        $entityManager->flush();

        return $this->redirectToRoute('app_covoiturages');

    }

    #[Route('/covoiturage/v/{id}', name: 'app_detail_covoiturage')]
    public function detail(
        int $id, 
        Request $request, 
        EntityManagerInterface $entityManager,
        CovoiturageRepository $covoiturageRepository, 
        ParticipationRepository $participationRepository, 
        DocumentManager $documentManager,
    ): Response
    {

        /** @var User $user */
        $user = $this->getUser();
        
        $covoiturage = $covoiturageRepository->find($id);
        
        $participation = $participationRepository->findOneBy([
            'passager' => $user,
            'covoiturage' => $covoiturage
        ]);

        $avis = $documentManager->getRepository(Avis::class)->findBy([
            'chauffeur' => $covoiturage->getVoiture()->getChauffeur()->getId()
        ]);
        

        $form = $this->createForm(DetailFormType::class);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            $this->denyAccessUnlessGranted('ROLE_USER');
    
            $participation = new Participation();    
            $participation->setPassager($user);
            $participation->setCovoiturage($covoiturage);
            $participation->setStatut('inscrit');

            $user->setCredits($user->getCredits() - $covoiturage->getPrixpersonne());            
            
            $covoiturage->setNbPlace($covoiturage->getNbPlace() - 1);

            $entityManager->persist($participation);
            $entityManager->persist($user);
            $entityManager->persist($covoiturage);
            $entityManager->flush();

            return $this->redirectToRoute('app_participations');

        }

        return $this->render('covoiturage/detail.html.twig', [
            'controller_name' => 'CovoiturageController',
            'detailForm' => $form,
            'covoiturage' => $covoiturage,
            'user' => $user,
            'participation' => $participation,
            'avis' => $avis
        ]);

    }

    #[Route('/covoiturage/u/{id}', name: 'app_update_covoiturage')]
    public function edit(
        int $id, 
        Request $request, 
        CovoiturageRepository $covoiturageRepository, 
        ItineraireService $itineraireService, 
        EntityManagerInterface $entityManager
    ): Response
    {

        $covoiturage = $covoiturageRepository->find($id);

        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(CovoiturageFormType::class, $covoiturage, [
            'depart' => $covoiturage->getLieuDepart()->getLibelle(),
            'arrivee' => $covoiturage->getLieuArrivee()->getLibelle(),
            'chauffeur' => $user
        ]);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($covoiturage);
            $entityManager->flush();

            return $this->redirectToRoute('app_covoiturages');

        }

        $villes = $itineraireService->getVilles();

        return $this->render('covoiturage/index.html.twig', [
            'controller_name' => 'CovoiturageController',
            'covoiturageForm' => $form,
            'user' => $user,
            'action' => 'Modifier',
            'villes' => $villes
        ]);

    }
    
    #[Route('/covoiturage/c', name: 'app_create_covoiturage')]
    public function new(
        Request $request, 
        ItineraireService $itineraireService, 
        EntityManagerInterface $entityManager,
    ): Response
    {
        
        $covoiturage = new Covoiturage();
        
        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(CovoiturageFormType::class, $covoiturage, ['chauffeur' => $user]);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {

            $lieu_depart = $form->get('lieu_depart')->getData();
            $lieu_arrivee = $form->get('lieu_arrivee')->getData();

            $covoiturage->setLieuDepart($itineraireService->getOrCreateVille($lieu_depart));
            $covoiturage->setLieuArrivee($itineraireService->getOrCreateVille($lieu_arrivee));
            $covoiturage->setStatut('planifié');

            $entityManager->persist($covoiturage);
            $entityManager->flush();

            return $this->redirectToRoute('app_covoiturages', [
                'lieu_depart' => $lieu_depart,
                'lieu_arrivee' => $lieu_arrivee
            ]);

        }

        $villes = $itineraireService->getVilles();

        return $this->render('covoiturage/index.html.twig', [
            'controller_name' => 'CovoiturageController',
            'covoiturageForm' => $form,
            'user' => $user,
            'action' => 'Créer',
            'villes' => $villes
        ]);
        
    }

    #[Route('/covoiturages', name: 'app_covoiturages')]
    public function covoiturages(
        Request $request, 
        ItineraireService $itineraireService, 
    ): Response
    {

        $villes = $itineraireService->getVilles();

        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(ItineraireFormType::class, null);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {

        }

        $covoiturages = $itineraireService->getCovoituragesByChauffeur($user);

        return $this->render('covoiturage/list.html.twig', [
            'covoiturageForm' => $form,
            'controller_name' => 'CovoiturageController',
            'user' => $user,
            'covoiturages' => $covoiturages,
            'nouveau' => true,
            'villes' => $villes,
            'type' => 'Mes propositions de covoiturages',
            'date_depart' => null
        ]);

    }

    #[Route('/participations', name: 'app_participations')]
    public function participations(
        Request $request, 
        ItineraireService $itineraireService, 
    ): Response
    {

        $villes = $itineraireService->getVilles();

        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(FiltresFormType::class, null, [
            'ecologique' => false
        ]);
        $form->handleRequest($request);
        
        $covoiturages = $itineraireService->gatParticipations($user);

        return $this->render('covoiturage/list.html.twig', [
            'covoiturageForm' => $form,
            'controller_name' => 'CovoiturageController',
            'user' => $user,
            'covoiturages' => $covoiturages,
            'nouveau' => false,
            'villes' => $villes,
            'type' => 'Mes participations à des covoiturages',
            'date_depart' => null
        ]);

    }

    #[Route('/itineraires', name: 'app_itineraires')]
    public function itineraires(
        Request $request, 

templates/covoiturage/carte.html.twig
<div class="card mb-3 p-0 carte-covoiturage">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="photos/{{ covoiturage.voiture.chauffeur.photo }}" height="140px"/>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-text">{{ covoiturage.dateDepart|date("d/m/Y") }} : {{ covoiturage.lieuDepart.libelle }} => {{ covoiturage.lieuArrivee.libelle }} à {{ covoiturage.prixPersonne }} crédit(s)</h5>
                <p class="card-text">{{ covoiturage.voiture.chauffeur.pseudo }} conduit une {{ covoiturage.voiture.modele }} {{ covoiturage.voiture.marque.libelle }} {{ covoiturage.voiture.couleur }} {{ covoiturage.voiture.energie.libelle }}</p>
                <p class="card-text">Il reste {{ covoiturage.nbPlace }} place(s). Départ {{ covoiturage.heureDepart|date("H:i") }} arrivée le {{ covoiturage.dateArrivee|date("d/m/Y") }} à {{ covoiturage.heureArrivee|date("H:i") }}</p>
                {% if nouveau %}
                    {% if covoiturage.statut == 'planifié' %}
                        <a href="{{ url('app_delete_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Supprimer</a>
                        <a href="{{ url('app_update_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Modifier</a>
                        <a href="{{ url('app_statut_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Démarrer</a>
                    {% endif %}
                    {% if covoiturage.statut == 'démarré' %}
                        <a href="{{ url('app_statut_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Arrivé à destination</a>
                    {% endif %}
                {% else %}
                    <a href="{{ url('app_detail_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Détail</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/covoiturage/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail covoiturage{% endblock %}

{% block body %}

    <div class="container my-5 p-0">

        <h1>{{ covoiturage.dateDepart|format_datetime('full', 'none', locale: 'en') }}</h1>
        <p id="covoiturage_id" class="card-text">{{ covoiturage.id  }}</p>

        <div class="d-flex flex-column flex-lg-row">

            <div class="col-12 col-lg-8 p-0 p-lg-4">

                <div class="card mb-3 p-0">
                    <div class="card-body">
                        <div class="d-flex">
                            <div style="padding: 0px 15px 0px 0px">
                                <p class="card-text"><b>{{ covoiturage.heureDepart|date("H:i") }}</b></p>
                                <p class="card-text"><b>{{ covoiturage.heureArrivee|date("H:i") }}</b></p>
                            </div>
                            <div class="d-flex flex-column justify-content-between">
                                <div style="border: 2px black solid; border-radius: 50%; width: 10px; height: 10px; margin-top: 0.5rem"></div>
                                <div style="border: 2px black solid; margin: 0 3px; width: 0px; height: 1.9rem"></div>
                                <div style="border: 2px black solid; border-radius: 50%; width: 10px; height: 10px; margin-bottom: 1rem"></div>
                            </div>
                            <div style="padding: 0px 0px 0px 15px">
                                <p class="card-text"><b>{{ covoiturage.lieuDepart.libelle }}</b></p>
                                <p class="card-text"><b>{{ covoiturage.lieuArrivee.libelle }}</b></p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-3 p-0">
                    <div class="card-body">
                        <div class="d-flex">
                            <img src="/photos/{{ covoiturage.voiture.chauffeur.photo }}" class="img-fluid" alt="{{ covoiturage.voiture.chauffeur.pseudo }}" style="height: 140px; width: aauto;">
                            <p class="card-text" style="padding: 8px"><b>{{ covoiturage.voiture.chauffeur.pseudo }}</b></p>
                        </div>
                        <hr>
                        <p class="card-text">{{ covoiturage.voiture.modele }} {{ covoiturage.voiture.marque.libelle }} {{ covoiturage.voiture.couleur }} {{ covoiturage.voiture.energie.libelle }}</p>
                        <p class="card-text">Il reste {{ covoiturage.nbPlace }} place(s)</p>
                        <input type="checkbox" class="form-check-input" id="ecologique" name="ecologique" {% if covoiturage.voiture.energie.ecologique %}checked{% endif %} disabled />
                        <label for="ecologique">Ecologique</label>
                        <input type="checkbox" class="form-check-input" id="fumeur" name="fumeur" {% if covoiturage.voiture.fumeur %}checked{% endif %} disabled />
                        <label for="fumeur">Fumeur</label>
                        <input type="checkbox" class="form-check-input" id="animal" name="animal" {% if covoiturage.voiture.animal %}checked{% endif %} disabled />
                        <label for="animal">Animaux</label>
                    </div>
                </div>

            </div>

            <div class="d-flex flex-column col-12 col-lg-4 p-0 p-lg-4">

                <div class="card mb-3 p-0">
                    <div class="card-body">
                        <div class="d-flex">
                            <div style="padding: 0px 15px 0px 0px">
                                <p class="card-text"><b>{{ covoiturage.heureDepart|date("H:i") }}</b></p>
                                <p class="card-text"><b>{{ covoiturage.heureArrivee|date("H:i") }}</b></p>
                            </div>
                            <div class="d-flex flex-column justify-content-between">
                                <div style="border: 2px black solid; border-radius: 50%; width: 10px; height: 10px; margin-top: 0.5rem"></div>
                                <div style="border: 2px black solid; margin: 0 3px; width: 0px; height: 1.9rem"></div>
                                <div style="border: 2px black solid; border-radius: 50%; width: 10px; height: 10px; margin-bottom: 1rem"></div>
                            </div>
                            <div style="padding: 0px 0px 0px 15px">
                                <p class="card-text"><b>{{ covoiturage.lieuDepart.libelle }}</b></p>
                                <p class="card-text"><b>{{ covoiturage.lieuArrivee.libelle }}</b></p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="card mb-3 p-0">
                    <div class="d-flex justify-content-between p-2">
                        <p class="card-text"><b>1 passager</b></p>
                        <p class="card-text"><b>{{ covoiturage.prixPersonne }} crédits</b></p>
                    </div>
                </div>
                    
                {% if participation != null %}
                    {% if participation.statut == 'inscrit' %}
                        {% if covoiturage.statut == 'arrivé' %}
                            <a href="{{ url('app_valider_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Valider le voyage</a>
                        {% else %}
                            <a href="{{ url('app_annuler_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary">Annuler</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if user is not defined or user == null or (user != covoiturage.voiture.chauffeur and user.credits >= covoiturage.prixPersonne) %}
                        <button id="bouton_action" type="button" class="btn btn-primary my-1" data-bs-toggle="modal" data-bs-target="#modalParticiper">
                            participer
                        </button>
                    {% endif %}
                {% endif %}

            </div>

        </div>

        <h4>Avis</h4>

        <div>
            {% for avi in avis %}      
                {% include 'avis/avis.html.twig' with {'avis': avi, 'covoiturage': covoiturage} only %}
            {% endfor %}
        </div>

        <a href="{{ url('app_itineraires') }}" class="btn btn-primary col-12 col-lg-1 my-1">Retour</a>

    </div>

    <div class="modal fade" id="modalParticiper" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Validation</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Vous allez participer au covoiturage {{ covoiturage.lieuDepart.libelle }} => {{ covoiturage.lieuArrivee.libelle }} du {{ covoiturage.dateDepart|format_datetime('full', 'none', locale: 'en') }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <button class="btn btn-primary" data-bs-target="#modalValidation" data-bs-toggle="modal">Continuer</button>
            </div>
            </div>
        </div>
    </div>

    {{ form_start(detailForm) }}

    <div class="modal fade" id="modalValidation" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Paiement</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Votre solde va être débité de {{ covoiturage.prixPersonne }} crédit(s) !
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <button id="payer" class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Payer</button>
                {# <a href="{{ url('app_action_covoiturage', {id: covoiturage.id}) }}" class="btn btn-primary mx-2">Payer</a> #}
            </div>
            </div>
        </div>
    </div>

    {{ form_end(detailForm) }}

{% endblock %}

templates/covoiturage/filtres.html.twig
<div class="card p-0 carte-filtres">

    <div class="card-body ">

        <h3 class="card-title">Filtres</h3>

            <div class="form-group mx-2 my-3">
                {{ form_row(covoiturageForm.ecologique) }}
            </div>
            <div class="form-group mx-2 my-3">
                {{ form_row(covoiturageForm.prix_personne) }}
            </div>
            <div class="form-group mx-2 my-3">
                {{ form_row(covoiturageForm.duree_voyage) }}
            </div>
            <div class="form-group mx-2 my-3">
                {{ form_row(covoiturageForm.note_chauffeur) }}
            </div>

            <button class="btn btn-outline-primary" type="submit" id="itineraire-submit">Filtrer</button>

    </div>

</div>

templates/covoiturage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voitures{% endblock %}

{% block body %}

    {{ form_errors(covoiturageForm) }}

    <div class="container my-5">

        <h1 class="h3 mb-3 font-weight-normal">Ajoutez un covoiturage</h1>

        {{ form_start(covoiturageForm) }}

            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.lieu_depart) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.date_depart) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.heure_depart) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.lieu_arrivee) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.date_arrivee) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.heure_arrivee) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.nb_place) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.prix_personne) }}
            </div>
            <div class="form-group mx-5 my-3">
                {{ form_row(covoiturageForm.voiture) }}
            </div>

            <div class="d-flex mx-5 mt-3 mb-5">
                <button type="submit" class="btn btn-primary">{{ action }}</button>
                <a href="{{ url('app_covoiturages') }}" class="btn btn-primary mx-2">Abandonner</a>
            </div>

            <datalist id="list-ville">
                {% for ville in villes %}      
                    <option data="{{ ville.id }}" value="{{ ville.libelle }}"></option>
                {% endfor %}
            </datalist>

        {{ form_end(covoiturageForm) }}

    </div>

{% endblock %}

templates/covoiturage/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cooitureags{% endblock %}

{% block body %}

    <div class="container my-5 p-0">

        <h1 class="h3 mb-3 font-weight-normal">{{ type }}</h1>

        {{ form_start(covoiturageForm) }}
            
            <div class="p-0">

                <div class="d-flex flex-column flex-lg-row mb-3">

                    {% include 'covoiturage/itineraire.html.twig' with {'villes': villes} %}

                    <button class="btn btn-outline-primary my-1" type="submit" id="itineraire-submit"><i class="bi bi-search"></i></button>

                </div>

                <div class="d-flex flex-column-reverse flex-lg-row">

                    {% if not nouveau %}

                        <div class="p-0 p-lg-3 col-12 col-lg-3">
                        
                            {% include 'covoiturage/filtres.html.twig' %}

                        </div>

                    {% endif %}

                    <div class="p-0 p-lg-3 {% if nouveau %}col-12{% else %}col-12 col-lg-9{% endif %}">

                        {% if nouveau %}
                            {% include 'covoiturage/new.html.twig' %}
                        {% endif %}

                        {% for covoiturage in covoiturages %}
                            {% if date_depart == null or covoiturage.dateDepart|date("Y-m-d") == date_depart|date('Y-m-d') or loop.index == 0 %}
                                {% include 'covoiturage/carte.html.twig' %}
                            {% endif %}
                        {% endfor %}

                    </div>

                </div>

            </div>

        {{ form_end(covoiturageForm) }}

    </div>

{% endblock %}